import { Plans } from "./landing";

export const Plan = () => {
  const website1 = [
    {
      title: "dynamic 5 page website",
      title2: "350 AED",
      feat1: "domain not included",
      feat2: "wordpress website",
      feat3: "CMS & KT will be provided",
      feat4: "free hosting for first year",
      feat5: "second years charges applicaple",
      feat6: "GMB intergration",
      feat7: "social media & watsapp integration",
      feat8: "server space-5GB",
      feat9: "5 bussiness emails",
    },
  ];
  const website2 = [
    {
      title: "dynamic 5 page website",
      title2: "450 AED",
      feat1: "domain purchase included",
      feat2: "wordpress website",
      feat3: "CMS & KT will be provided",
      feat4: "free hosting for first year",
      feat5: "second years charges applicaple",
      feat6: "GMB intergration",
      feat7: "social media & watsapp integration",
      feat8: "server space-20GB",
      feat9: "unlimtted bussiness emails",
    },
  ];
  const website = [
    {
      title: "dynamic 5 page website",
      title2: "350 AED",
      feat1: "domain not included",
      feat2: "wordpress website",
      feat3: "CMS & KT will be provided",
      feat4: "free hosting for first year",
      feat5: "second years charges applicaple",
      feat6: "GMB intergration",
      feat7: "social media & watsapp integration",
      feat8: "server space-5GB",
      feat9: "5 bussiness emails",
    },

    {
      title: "dynamic 5 page website",
      title2: "450 AED",
      feat1: "domain purchase included",
      feat2: "wordpress website",
      feat3: "CMS & KT will be provided",
      feat4: "free hosting for first year",
      feat5: "second years charges applicaple",
      feat6: "GMB intergration",
      feat7: "social media & watsapp integration",
      feat8: "server space-20GB",
      feat9: "unlimtted bussiness emails",
    },
  ];
  const seo = [
    {
      title: "basic",
      title2: "750 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 5",
      feat3: "One page-Optimization",
      feat4: "Reports-Monthly",
      feat5: "Blog submission - 10",
      feat6: "backlink analysis & generation - 25",
      feat7: "minimum contact - 6 months",
      feat8: "customer support -Email,zoom,botim",
      feat9: "",
      feat10: "",
      feat11: "",
      feat12: "",
      feat13: "",
    },
    {
      title: "advanced",
      title2: "1250 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 15",
      feat3: "One page-Optimization",
      feat4: "Reports-Monthly",
      feat5: "Blog submission - 20",
      feat6: "backlink analysis & generation - 75",
      feat7: "minimum contact - 6 months",
      feat8: "customer support -Email,zoom,botim",
      feat9: "",
      feat10: "",
      feat11: "",
      feat12: "",
      feat13: "",
    },

    {
      title: "premium",
      title2: "2000 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 30",
      feat3: "One page-Optimization",
      feat4: "basic technical SEO audit",
      feat5: "GMB setup",
      feat6: "Reports-(Bi-weekly)",
      feat7: "Blog submission - 35",
      feat8: "backlink analysis & generation - 150",
      feat9: "local SEO optimaization",
      feat10: "technical SEO optimization",
      feat11: "dedicated account manager",
      feat12: "minimum contract -6 months",
      feat13: "customer support -Email,zoom,botim",
    },
    {
      title: "enterprise",
      title2: "3500 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 50",
      feat3: "One page-Optimization",
      feat4: "basic technical SEO audit",
      feat5: "GMB setup",
      feat6: "Reports-weekly",
      feat7: "Blog submission - 50",
      feat8: "backlink analysis & generation - 200",
      feat9: "local SEO optimaization",
      feat10: "technical SEO optimization",
      feat11: "dedicated account manager",
      feat12: "minimum contract -6 months",
      feat13: "customer support -Email,zoom,botim",
    },
  ];

  const seo1 = [
    {
      title: "basic",
      title2: "750 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 5",
      feat3: "One page-Optimization",
      feat4: "Reports-Monthly",
      feat5: "Blog submission - 10",
      feat6: "backlink analysis & generation - 25",
      feat7: "minimum contact - 6 months",
      feat8: "customer support -Email,zoom,botim",
      feat9: "",
      feat10: "",
      feat11: "",
      feat12: "",
      feat13: "",
    },
  ];
  const seo2 = [
    {
      title: "advanced",
      title2: "1250 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 15",
      feat3: "One page-Optimization",
      feat4: "Reports-Monthly",
      feat5: "Blog submission - 20",
      feat6: "backlink analysis & generation - 75",
      feat7: "minimum contact - 6 months",
      feat8: "customer support -Email,zoom,botim",
      feat9: "",
      feat10: "",
      feat11: "",
      feat12: "",
      feat13: "",
    },
  ];

  const seo3 = [
    {
      title: "premium",
      title2: "2000 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 30",
      feat3: "One page-Optimization",
      feat4: "basic technical SEO audit",
      feat5: "GMB setup",
      feat6: "Reports-(Bi-weekly)",
      feat7: "Blog submission - 35",
      feat8: "backlink analysis & generation - 150",
      feat9: "local SEO optimaization",
      feat10: "technical SEO optimization",
      feat11: "dedicated account manager",
      feat12: "minimum contract -6 months",
      feat13: "customer support -Email,zoom,botim",
    },
  ];
  const seo4 = [
    {
      title: "enterprise",
      title2: "3500 AED",
      feat1: "keyword research",
      feat2: "No.of Keywords - 50",
      feat3: "One page-Optimization",
      feat4: "basic technical SEO audit",
      feat5: "GMB setup",
      feat6: "Reports-weekly",
      feat7: "Blog submission - 50",
      feat8: "backlink analysis & generation - 200",
      feat9: "local SEO optimaization",
      feat10: "technical SEO optimization",
      feat11: "dedicated account manager",
      feat12: "minimum contract -6 months",
      feat13: "customer support -Email,zoom,botim",
    },
  ];
  const smm = [
    {
      title: "basic",
      title2: "170 AED",
      platform: "2(Facebook & Instagram)",
      posts: "up to 10 posts",
      feat: "corporate bonding",
      feat1: "",
      feat2: "",
      feat3: "",
      feat4: "",
      feat5: "",
      feat6: "",
      feat7: "",
      feat8: "",
    },
    {
      title: "advanced",
      title2: "1250 AED",
      platform: "3(Facebook & Instagram,Twitter)",
      posts: "up to 15 posts",
      feat: "corporate bonding",
      feat1: "number of video creation(30s)-1",
      feat2: "social media audit",
      feat3: "audience analysis",
      feat4: "Hastag research",
      feat5: "",
      feat6: "",
      feat7: "",
      feat8: "",
    },
    {
      title: "premium",
      title2: "2000 AED",
      platform: "4(Facebook & Instagram,Twitter,Linkedin)",
      posts: "up to 20 posts",
      feat: "corporate bonding",
      feat1: "number of video creation(30s)-2",
      feat2: "social media audit",
      feat3: "audience analysis",
      feat4: "Hastag research",
      feat5: "ad campaign setup",
      feat6: "cutomized capmigns",
      feat7: "A/B Testing",
      feat8: "competitor analysis",
    },
    {
      title: "enterprise",
      title2: "3000 AED",
      platform: "4(Facebook & Instagram,Twitter,Linkedin)",
      posts: "up to 20 posts",
      feat: "corporate bonding",
      feat1: "number of video creation(30s)-2",
      feat2: "social media audit",
      feat3: "audience analysis",
      feat4: "Hastag research",
      feat5: "ad campaign setup",
      feat6: "cutomized capmigns",
      feat7: "A/B Testing",
      feat8: "competitor analysis",
    },
  ];

  const smm1 = [
    {
      title: "basic",
      title2: "170 AED",
      platform: "2(Facebook & Instagram)",
      posts: "up to 10 posts",
      feat: "corporate bonding",
      feat1: "",
      feat2: "",
      feat3: "",
      feat4: "",
      feat5: "",
      feat6: "",
      feat7: "",
      feat8: "",
    },
  ];

  const smm2 = [
    {
      title: "advanced",
      title2: "1250 AED",
      platform: "3(Facebook & Instagram,Twitter)",
      posts: "up to 15 posts",
      feat: "corporate bonding",
      feat1: "number of video creation(30s)-1",
      feat2: "social media audit",
      feat3: "audience analysis",
      feat4: "Hastag research",
      feat5: "",
      feat6: "",
      feat7: "",
      feat8: "",
    },
  ];
  const smm3 = [
    {
      title: "premium",
      title2: "2000 AED",
      platform: "4(Facebook & Instagram,Twitter,Linkedin)",
      posts: "up to 20 posts",
      feat: "corporate bonding",
      feat1: "number of video creation(30s)-2",
      feat2: "social media audit",
      feat3: "audience analysis",
      feat4: "Hastag research",
      feat5: "ad campaign setup",
      feat6: "cutomized capmigns",
      feat7: "A/B Testing",
      feat8: "competitor analysis",
    },
  ];

  const smm4 = [
    {
      title: "enterprise",
      title2: "3000 AED",
      platform: "4(Facebook & Instagram,Twitter,Linkedin)",
      posts: "up to 20 posts",
      feat: "corporate bonding",
      feat1: "number of video creation(30s)-2",
      feat2: "social media audit",
      feat3: "audience analysis",
      feat4: "Hastag research",
      feat5: "ad campaign setup",
      feat6: "cutomized capmigns",
      feat7: "A/B Testing",
      feat8: "competitor analysis",
    },
  ];

  return (
    <div className="mt-10">
      <Plans web={{website, website1, website2, seo,seo1,seo2,seo3,seo4, smm,smm1,smm2,smm3,smm4 }} />
    </div>
  );
};
